//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotspotShare {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotspotShare.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspot Share.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotspotShare cannot find a wireless device. Please consider enabling your wireless device if there is any.
        ///The application will not function without a wireless device attached..
        /// </summary>
        internal static string App_NoWireless {
            get {
                return ResourceManager.GetString("App_NoWireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspot Share is already running and you can find its icon in system tray..
        /// </summary>
        internal static string App_OneInstance {
            get {
                return ResourceManager.GetString("App_OneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is minimized..
        /// </summary>
        internal static string Balloon_Minimized {
            get {
                return ResourceManager.GetString("Balloon_Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new user is connected to hotspot share..
        /// </summary>
        internal static string Balloon_NewUser {
            get {
                return ResourceManager.GetString("Balloon_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Form_BtnStarted {
            get {
                return ResourceManager.GetString("Form_BtnStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Form_BtnStarting {
            get {
                return ResourceManager.GetString("Form_BtnStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Form_BtnStoped {
            get {
                return ResourceManager.GetString("Form_BtnStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string Form_BtnStopping {
            get {
                return ResourceManager.GetString("Form_BtnStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change the application language to &apos;English&apos;?
        ///Application will restart to apply the changes..
        /// </summary>
        internal static string Form_ConfirmLanguageEn {
            get {
                return ResourceManager.GetString("Form_ConfirmLanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change the application language to &apos;فارسی&apos;?
        ///Application will restart to apply the changes..
        /// </summary>
        internal static string Form_ConfirmLanguageFa {
            get {
                return ResourceManager.GetString("Form_ConfirmLanguageFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to share is not selected..
        /// </summary>
        internal static string Form_ConnectionSelected {
            get {
                return ResourceManager.GetString("Form_ConnectionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string Form_InvalidInput {
            get {
                return ResourceManager.GetString("Form_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long..
        /// </summary>
        internal static string Form_PassLong {
            get {
                return ResourceManager.GetString("Form_PassLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Form_PassRequired {
            get {
                return ResourceManager.GetString("Form_PassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be at least 8 characters..
        /// </summary>
        internal static string Form_PassShort {
            get {
                return ResourceManager.GetString("Form_PassShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID is too long..
        /// </summary>
        internal static string Form_SSIDLong {
            get {
                return ResourceManager.GetString("Form_SSIDLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSID is required..
        /// </summary>
        internal static string Form_SSIDRequired {
            get {
                return ResourceManager.GetString("Form_SSIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Form_StartedStated {
            get {
                return ResourceManager.GetString("Form_StartedStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Form_StopedStated {
            get {
                return ResourceManager.GetString("Form_StopedStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # source: https://svn.nmap.org/nmap/nmap-mac-prefixes
        ///# $Id$ generated with make-mac-prefixes.pl
        ///# Original data comes from http://standards.ieee.org/regauth/oui/oui.txt
        ///# These values are known as Organizationally Unique Identifiers (OUIs)
        ///# See http://standards.ieee.org/faqs/OUI.html
        ///# We have added a few unregistered OUIs at the end.
        ///000000 Xerox
        ///000001 Xerox
        ///000002 Xerox
        ///000003 Xerox
        ///000004 Xerox
        ///000005 Xerox
        ///000006 Xerox
        ///000007 Xerox
        ///000008 Xerox
        ///000009 Xerox
        ///00000A Omron Tateisi Electronics CO.
        ///00000B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nmap_mac_prefixes {
            get {
                return ResourceManager.GetString("nmap_mac_prefixes", resourceCulture);
            }
        }
    }
}
